package stream.rocketnotes;

public interface Constants {
    String APP_NAME = "Rocket Note";
    String APP_VERSION = "1.0.8";
    String YEAR = "2017";
    Integer TITLE_LENGTH = 40;
    Integer RECENT_IMAGES = 8;
    Integer RECENT_NOTES = 40;
    String QUICK_NOTE = "QUICK_NOTE";
    String OPEN_APP = "OPEN_APP";
    String NEW_NOTE = "NEW_NOTE";
    String OPEN_NOTE = "OPEN_NOTE";
    String ADD_IMAGE = "ADD_IMAGE";
    String OPEN_IMAGE = "OPEN_IMAGE";
    String OPEN_IMAGE_SINGLE = "OPEN_IMAGE_SINGLE";
    String UPDATE_NOTE = "UPDATE_NOTE";
    String DELETE_NOTE = "DELETE_NOTE";
    String ADDTO_NOTE = "ADDTO_NOTE";
    String HIDE_REVIEW = "HIDE_REVIEW";
    String REFRESH = "REFRESH";
    String BODY = "BODY";
    String TEXT = "TEXT";
    String IMAGE = "IMAGE";
    String ID = "ID";
    String RECEIVED = "RECEIVED";
    String FILTER = "FILTER";
    String FILTER_IMAGES = "FILTER_IMAGES";
    String STICKY = "STICKY";
    String SOURCE_PATH = "SOURCE_PATH";
    String SAVE_PATH = "SAVE_PATH";
    String WIDGET_REVIEW = "WIDGET_REVIEW";
    String WIDGET_REVIEW_HIDE = "WIDGET_REVIEW_HIDE";
    String URL = "URL";
    String TITLE = "TITLE";
    String AUTHORITY = "stream.rocketnotes.provider";
    String FIREBASE_USER_ID = "FIREBASE_USER_ID";
    String UXCAM_API_KEY = "0cbfb20ca44be10";
    Boolean ANALYTICS_ENABLED = false;
}
